version: '3.9'

networks:
  web_network:
    external: true
  daft-fm-network:
    external: true
  central-auth-network:
    external: true
services:
  daft-fm-app:
    build:
      context: ../..
      dockerfile: ./apps/daft-fm/Dockerfile
    container_name: daft-fm-app
    restart: unless-stopped
    networks:
      - web_network
      - daft-fm-network
      - central-auth-network
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - ROBOTS_ENV=production
      - NUXT_SITE_ENV=production
      - NUXT_PUBLIC_SITE_URL=https://daft.fm
      - DATABASE_URL=${DATABASE_URL}
      - NUXT_PUBLIC_API_URL=${NUXT_PUBLIC_API_URL}
      - NUXT_PUBLIC_DOMAIN=${NUXT_PUBLIC_DOMAIN}
      - NUXT_PUBLIC_SITE_NAME=${NUXT_PUBLIC_SITE_NAME}
      - NUXT_PUBLIC_URL=${NUXT_PUBLIC_URL}
      - AUTH_ORIGIN=${NUXT_PUBLIC_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - REDIS_URL=redis://daft-fm-redis:6379
    depends_on:
      - daft-fm-redis
  daft-fm-redis:
    image: redis:7.2.5
    container_name: daft-fm-redis
    restart: unless-stopped
    networks:
      - daft-fm-network
