version: '3.9'
services:
  serp-monorepo-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: serp-monorepo-dev
    command: ${DOCKER_CMD:-pnpm dev}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/boxingundefeated-com/node_modules
      - /app/apps/serp-co/node_modules
      - /app/apps/serp-media/node_modules
      - /app/packages/tools/node_modules
      - /app/packages/types/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/utils/node_modules
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=development
      - ROBOTS_ENV=development
      - NUXT_SITE_ENV=development
      - NUXT_PUBLIC_SITE_URL=http://localhost:3000
      - DATABASE_URL=${DATABASE_URL}
      - NUXT_PUBLIC_API_URL=${NUXT_PUBLIC_API_URL}
      - NUXT_PUBLIC_DOMAIN=${NUXT_PUBLIC_DOMAIN}
      - NUXT_PUBLIC_SITE_NAME=${NUXT_PUBLIC_SITE_NAME}
      - NUXT_PUBLIC_URL=${NUXT_PUBLIC_URL}