blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/serpcompany/serp-monorepo/blob/main/CLAUDE.md
    about: Check project rules and guidelines
  - name: 💬 Discussions
    url: https://github.com/serpcompany/serp-monorepo/discussions
    about: Ask questions and discuss ideas