[build]
  publish = ".output/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22.16.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.deploy-preview]
  environment = { NODE_ENV = "production", ROBOTS_ENV = "staging", NUXT_SITE_ENV = "preview" }

[context.branch-deploy]
  environment = { NODE_ENV = "production", ROBOTS_ENV = "staging", NUXT_SITE_ENV = "preview" }