#!/bin/sh

# Start
echo "[husky]: Running pre-commit hook..."

# Check staged files
STAGED_FILES=$(git diff --cached --name-only)
echo "[husky]: Your staged files: $STAGED_FILES"

# Run lint-staged to lint only staged files
echo "[husky]: Running script: pnpm lint"
pnpm lint

# Run tests
echo "[husky]: Running script: pnpm test"
pnpm test

# # Run secret scan check with Trufflehog
# echo "[husky]: Running script: pnpm scan:secrets"
# pnpm scan:secrets
