name: build_staging_serp_co

on:
  push:
    paths:
      - packages/**
      - apps/serp_co/**
    branches:
      - staging
  workflow_dispatch:

jobs:
  build_staging_serp_co:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.FRANCIS_SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd serp-monorepo-staging/apps/serp_co
            docker compose -f docker-compose-staging.yml down
            git pull https://${{ secrets.DEVIN_GITHUB_TOKEN }}@github.com/${{github.repository}}.git ${{ github.ref_name }}
            infisical run --domain=https://secrets.serp.co --token=${{ secrets.INFISICAL_ACCESS_TOKEN_SERP_CO }} --projectId=${{ secrets.INFISICAL_PROJECT_ID_SERP_CO }} -- docker compose -f docker-compose-staging.yml up --build -d
