name: ci_1_pr
# All snapshots committed - CI should pass now

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '.coderules/**'
      - 'misc/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  pr_standardization_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22.16.0]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: pr-test-${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Lint
        run: pnpm ci:lint

      - name: Test
        run: pnpm test

      - name: TypeScript Check - No TS7006 errors
        run: pnpm typecheck:ts7006

      - name: ESLint Check - No missing return types
        run: pnpm lint:return-types
