name: build_production_serp_ai

on:
  push:
    paths:
      - packages/**
      - apps/serp-ai/**
    branches:
      - main
  workflow_dispatch:

jobs:
  build_production_serp_ai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.FRANCIS_SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd serp-monorepo/apps/serp-ai
            docker compose -f docker-compose.yml down
            git pull https://${{ secrets.DEVIN_GITHUB_TOKEN }}@github.com/${{github.repository}}.git ${{ github.ref_name }}
            infisical run --domain=https://secrets.serp.co --token=${{ secrets.INFISICAL_ACCESS_TOKEN_SERP }} --projectId=${{ secrets.INFISICAL_PROJECT_ID_SERP_AI }} -- docker compose -f docker-compose.yml up --build -d
